In [3]:
my_list=[1,2,3]
my_list


[1, 2, 3]

In [5]:
import numpy as np 


In [9]:
arr=np.array(my_list)

In [25]:
arr

array([1, 2, 3])

In [31]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_2d = np.arange(50).reshape(5,10)

In [21]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
arr_2d[1:4,2:7]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36]])